In [1]:
import pandas as pd
import onca_utils as ou
import numpy as np
import json
import statistics as sts
import janitor
import os
import onca_products as op
import importlib
importlib.reload(ou)

<module 'onca_utils' from '/home/onca/onca_utils.py'>

In [2]:
# I/O paths
input_conapo_poblaciones = "./requirements/poblaciones_group_quinq.csv"
input_cat_entidades = "./requirements/entidades_fed.csv"
input_cat_municipios = "./requirements/municipios_geo.csv"
input_cat_edades = "./requirements/EDADES.csv"
input_mortality_folder = "../MORIN/MORTALIDAD/DATOS_CRUDOS/"
cie10 = "C16"

In [3]:
output_path = f'{cie10}_outputs'
if not os.path.exists(output_path):
    os.mkdir(output_path)
    
input_path = f'{cie10}_outputs'
if not os.path.exists(input_path):
    os.mkdir(input_path)

# Lectura de catalogos y datos crudos

In [4]:
print("Cargando catalogos")
catalog_loader = ou.CatalogLoader()
# Archivo de poblaciones
conapo_populations = catalog_loader.load_conapo_populations(input_conapo_poblaciones)

# Catalogo de entidades y municipios
cat_entidades = catalog_loader.load_states(input_cat_entidades)
cat_municipios = catalog_loader.load_municipalities(input_cat_municipios)
# Catalogo de edades
cat_edades = catalog_loader.load_ages(input_cat_edades)
del(catalog_loader)

Cargando catalogos


In [5]:
print("Cargando registros de mortalidad")
deaths = ou.DeathRegistryLoader().load_deaths(input_mortality_folder, cat_edades, cie10)
deaths = deaths[(deaths.ANIO_REGIS >= 2000) & (deaths.ANIO_REGIS != 9999)]

Cargando registros de mortalidad
Realizando extracción de registros para C16
Procesando archivo 2000.csv
Procesando archivo 2001.csv
Procesando archivo 2002.csv
Procesando archivo 2003.csv
Procesando archivo 2004.csv
Procesando archivo 2005.csv


/home/mcvolume/ONCA_v2/onca_utils.py:92: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  deaths = pd.read_csv(input_path)


Procesando archivo 2006.csv
Procesando archivo 2007.csv
Procesando archivo 2008.csv
Procesando archivo 2009.csv
Procesando archivo 2010.csv
Procesando archivo 2011.csv
Procesando archivo 2012.csv
Procesando archivo 2013.csv


/home/mcvolume/ONCA_v2/onca_utils.py:92: DtypeWarning: Columns (42,50) have mixed types. Specify dtype option on import or set low_memory=False.
  deaths = pd.read_csv(input_path)


Procesando archivo 2014.csv
Procesando archivo 2015.csv
Procesando archivo 2016.csv
Procesando archivo 2017.csv
Procesando archivo 2018.csv
Procesando archivo 2019.csv
Procesando archivo 2020.csv
Procesando archivo 2021.csv
Procesando archivo 2022.csv


/home/mcvolume/ONCA_v2/onca_utils.py:92: DtypeWarning: Columns (72) have mixed types. Specify dtype option on import or set low_memory=False.
  deaths = pd.read_csv(input_path)


In [6]:
mc = ou.MortalityCalculator()
pg = op.ProductGenerator()

In [7]:
df = mc.compute_raw_mortality_rate(deaths, conapo_populations, ['ANIO_REGIS'])#, 'RANGO_EDAD'])
df

ANIO_REGIS  DEFUNCIONES  POBLACION_ESTRATO  TASA_CRUDA_1K  TASA_CRUDA_10K  \
0         2000         5022           99368858       0.050539        0.505390   
1         2001         5028          100739263       0.049911        0.499110   
2         2002         5129          102167274       0.050202        0.502020   
3         2003         5153          103587899       0.049745        0.497452   
4         2004         5280          104970581       0.050300        0.502998   
5         2005         5326          106370948       0.050070        0.500701   
6         2006         5351          107885646       0.049599        0.495988   
7         2007         5340          109538665       0.048750        0.487499   
8         2008         5512          111275915       0.049535        0.495345   
9         2009         5490          113030218       0.048571        0.485711   
10        2010         5614          114756059       0.048921        0.489212   
11        2011         5551          116446180       0.047670        0.476701   
12        2012         5562          118060514       0.047111        0.471114   
13        2013         5596          119597654       0.046790        0.467902   
14        2014         5831          121048604       0.048171        0.481707   
15        2015         6060          122368490       0.049523        0.495226   
16        2016         6323          123587407       0.051162        0.511622   
17        2017         6293          124777172       0.050434        0.504339   
18        2018         6349          125995825       0.050391        0.503906   
19        2019         6447          127215666       0.050678        0.506777   
20        2020         6732          128209170       0.052508        0.525079   
21        2021         6672          128982939       0.051728        0.517278   
22        2022         6187          129960600       0.047607        0.476067   

    TASA_CRUDA_100K  
0          5.053897  
1          4.991103  
2          5.020199  
3          4.974519  
4          5.029981  
5          5.007006  
6          4.959881  
7          4.874991  
8          4.953453  
9          4.857108  
10         4.892116  
11         4.767009  
12         4.711143  
13         4.679022  
14         4.817073  
15         4.952255  
16         5.116217  
17         5.043390  
18         5.039056  
19         5.067772  
20         5.250794  
21         5.172777  
22         4.760674

In [8]:
# pg.create_lineplot(
#     data=df,
#     x='ANIO_REGIS',
#     y='TASA_CRUDA_100K',
#     color='RANGO_EDAD',
#     output_path=output_path,
#     cie10=cie10,
#     place='Mexico',
#     scale='100,000',
#     hover_data= ['TASA_CRUDA_100K'],
#     cve_geo='00',
#     sex='both sexes',
# )

In [9]:
deaths.ANIO_REGIS.unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022])

In [10]:
deaths[deaths.ANIO_REGIS == 9999]
years =  deaths.ANIO_REGIS.unique()

In [11]:
years
steps = 10
for steps in np.arange(1, len(years)):
    for i in np.arange(len(years)):
        if i + steps > len(years):
            break
        print(years[i:i+steps])

[2000]
[2001]
[2002]
[2003]
[2004]
[2005]
[2006]
[2007]
[2008]
[2009]
[2010]
[2011]
[2012]
[2013]
[2014]
[2015]
[2016]
[2017]
[2018]
[2019]
[2020]
[2021]
[2022]
[2000 2001]
[2001 2002]
[2002 2003]
[2003 2004]
[2004 2005]
[2005 2006]
[2006 2007]
[2007 2008]
[2008 2009]
[2009 2010]
[2010 2011]
[2011 2012]
[2012 2013]
[2013 2014]
[2014 2015]
[2015 2016]
[2016 2017]
[2017 2018]
[2018 2019]
[2019 2020]
[2020 2021]
[2021 2022]
[2000 2001 2002]
[2001 2002 2003]
[2002 2003 2004]
[2003 2004 2005]
[2004 2005 2006]
[2005 2006 2007]
[2006 2007 2008]
[2007 2008 2009]
[2008 2009 2010]
[2009 2010 2011]
[2010 2011 2012]
[2011 2012 2013]
[2012 2013 2014]
[2013 2014 2015]
[2014 2015 2016]
[2015 2016 2017]
[2016 2017 2018]
[2017 2018 2019]
[2018 2019 2020]
[2019 2020 2021]
[2020 2021 2022]
[2000 2001 2002 2003]
[2001 2002 2003 2004]
[2002 2003 2004 2005]
[2003 2004 2005 2006]
[2004 2005 2006 2007]
[2005 2006 2007 2008]
[2006 2007 2008 2009]
[2007 2008 2009 2010]
[2008 2009 2010 2011]
[2009 2010 2011 2012

In [12]:
for sex_id, sex in zip([1,2,3], ["Hombres","Mujeres","ambos sexos"]):
    for tasa, escala in zip(["TASA_CRUDA_1K","TASA_CRUDA_10K","TASA_CRUDA_100K"], ["1000","10,000","100,000"]):
        print(sex_id, sex, tasa, escala)

1 Hombres TASA_CRUDA_1K 1000
1 Hombres TASA_CRUDA_10K 10,000
1 Hombres TASA_CRUDA_100K 100,000
2 Mujeres TASA_CRUDA_1K 1000
2 Mujeres TASA_CRUDA_10K 10,000
2 Mujeres TASA_CRUDA_100K 100,000
3 ambos sexos TASA_CRUDA_1K 1000
3 ambos sexos TASA_CRUDA_10K 10,000
3 ambos sexos TASA_CRUDA_100K 100,000


In [13]:
deaths.sort_values("RANGO_EDAD").RANGO_EDAD.unique()

array(['00_04', '05_09', '10_14', '15_19', '20_24', '25_29', '30_34',
       '35_39', '40_44', '45_49', '50_54', '55_59', '60_64', '65_69',
       '70_74', '75_79', '80_84', '>85', 'NE'], dtype=object)

In [40]:
age_groups = ['00_04', '05_09', '10_14', '15_19', '20_24', '25_29', '30_34',
       '35_39', '40_44', '45_49', '50_54', '55_59', '60_64', '65_69',
       '70_74', '75_79', '80_84', '>85']
df = mc.compute_raw_mortality_rate(deaths[(deaths.RANGO_EDAD.isin(age_groups))], conapo_populations, ['ANIO_REGIS', 'RANGO_EDAD'])
# df = mc.compute_raw_mortality_rate(deaths[(deaths.RANGO_EDAD.isin(age_groups)) & (deaths.SEXO == 1)], conapo_populations, ['ANIO_REGIS', 'SEXO', 'RANGO_EDAD'])
# df = mc.compute_raw_mortality_rate(deaths, conapo_populations, ['ANIO_REGIS', 'RANGO_EDAD'])

In [41]:
df.RANGO_EDAD.unique()

array(['00_04', '05_09', '10_14', '15_19', '20_24', '25_29', '30_34',
       '35_39', '40_44', '45_49', '50_54', '55_59', '60_64', '65_69',
       '70_74', '75_79', '80_84', '>85'], dtype=object)

In [42]:
importlib.reload(ou)
who = ou.MortalityStandardizer(file_path='./requirements/poblaciones_WHO.csv', std_name='OMS', age_groups=age_groups)
# inegi = ou.MortalityStandardizer(file_path='./requirements/poblaciones_INEGI_2020.csv', std_name='INEGI', age_groups=age_groups)

In [43]:
who.compute_ASR(df=df[['ANIO_REGIS', 'RANGO_EDAD','TASA_CRUDA_100K']],
                age_column="RANGO_EDAD",
                rate_column="TASA_CRUDA_100K",
                scale="100K")

ANIO_REGIS  ASR(OMS)_100K
0         2000       7.766733
1         2001       7.509419
2         2002       7.432492
3         2003       7.226286
4         2004       7.168805
5         2005       7.009313
6         2006       6.814024
7         2007       6.556133
8         2008       6.551513
9         2009       6.307966
10        2010       6.238665
11        2011       5.955540
12        2012       5.771598
13        2013       5.603798
14        2014       5.641378
15        2015       5.683592
16        2016       5.749124
17        2017       5.537271
18        2018       5.406759
19        2019       5.315059
20        2020       5.417267
21        2021       5.288235
22        2022       4.791365