In [3]:
import pandas as pd
import numpy as np

In [87]:
age_groups = np.array(['00_04', '05_09', '10_14', '15_19', '20_24', '25_29', '30_34',
       '35_39', '40_44', '45_49', '50_54', '55_59', '60_64', '65_69',
       '70_74', '75_79', '80_84', '>85'])

In [93]:
age_groups = np.array([1,2,3,4,5])

In [94]:
age_groups[-1]

np.int64(5)

In [83]:
l=5
np.arange(arr_l-l+1)

array([0])

In [84]:
arr = np.array([1,2,3,4,5])
arr_l = arr.shape[0]

for l in np.arange(arr_l) + 1:   
    for i in np.arange(arr_l-l+1):
        print(arr[i:i+l])

[1]
[2]
[3]
[4]
[5]
[1 2]
[2 3]
[3 4]
[4 5]
[1 2 3]
[2 3 4]
[3 4 5]
[1 2 3 4]
[2 3 4 5]
[1 2 3 4 5]


In [92]:
arr_l = age_groups.shape[0]
counts = 0
for l in np.arange(arr_l) + 1:   
    for i in np.arange(arr_l-l+1):
        print(l, age_groups[i:i+l])
        counts += 1
print(counts)

1 ['00_04']
1 ['05_09']
1 ['10_14']
1 ['15_19']
1 ['20_24']
1 ['25_29']
1 ['30_34']
1 ['35_39']
1 ['40_44']
1 ['45_49']
1 ['50_54']
1 ['55_59']
1 ['60_64']
1 ['65_69']
1 ['70_74']
1 ['75_79']
1 ['80_84']
1 ['>85']
2 ['00_04' '05_09']
2 ['05_09' '10_14']
2 ['10_14' '15_19']
2 ['15_19' '20_24']
2 ['20_24' '25_29']
2 ['25_29' '30_34']
2 ['30_34' '35_39']
2 ['35_39' '40_44']
2 ['40_44' '45_49']
2 ['45_49' '50_54']
2 ['50_54' '55_59']
2 ['55_59' '60_64']
2 ['60_64' '65_69']
2 ['65_69' '70_74']
2 ['70_74' '75_79']
2 ['75_79' '80_84']
2 ['80_84' '>85']
3 ['00_04' '05_09' '10_14']
3 ['05_09' '10_14' '15_19']
3 ['10_14' '15_19' '20_24']
3 ['15_19' '20_24' '25_29']
3 ['20_24' '25_29' '30_34']
3 ['25_29' '30_34' '35_39']
3 ['30_34' '35_39' '40_44']
3 ['35_39' '40_44' '45_49']
3 ['40_44' '45_49' '50_54']
3 ['45_49' '50_54' '55_59']
3 ['50_54' '55_59' '60_64']
3 ['55_59' '60_64' '65_69']
3 ['60_64' '65_69' '70_74']
3 ['65_69' '70_74' '75_79']
3 ['70_74' '75_79' '80_84']
3 ['75_79' '80_84' '>85']
4 

In [4]:
3*3*171*1

1539